ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fiorella_second.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Views/Shared/_BasketPartial.cshtml
@model IEnumerable<Product>
<ul class="list-unstyled py-3" id="Basket">
    <li class="">No products in the cart.</li>
    @foreach (var item in Model)
    {  <li>
           <div class="cart-item cart-column">
               <a asp-action="Detail" asp-route-id="@item.Id">

                   <img class="cart-item-image" src="~/img/@item.Images.Where(i=>i.IsMain==true).FirstOrDefault().ImageUrl" width="100" height="100">


               </a>
               <span class="cart-item-title">@item.Title</span>
           </div>
    <span class="cart-price cart-column">@item.Price$</span>
    <div class="cart-quantity cart-column">
        <input class="cart-quantity-input" type="number" value="1">
        <button class="btn btn-danger" type="button">REMOVE</button>
    </div>
   
</li>
    }
</ul>

Views/Shared/_Layout.cshtml
@await Component.InvokeAsync("Header")
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    @await Component.InvokeAsync("Footer")

Views/Shared/_ProductPartial.cshtml
@model IEnumerable<Product>

@foreach (var card in Model)
{
    <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
        <div class="product-item text-center" data-id="@card.CategoryId">
            <div class="img">

                <a asp-action="Detail" asp-route-id="@card.Id">

                    <img src="~/img/@card.Images.Where(i=>i.IsMain==true).FirstOrDefault().ImageUrl" class="img-fluid" alt="">

                </a>
            </div>
            <div class="title mt-3">


                <h6>@card.Title</h6>

            </div>
            <div class="price">
                <form asp-controller="Product" asp-action="AddBasket" asp-route-id="@card.Id" method="post" class="d-inline">
                    <span class="text-black-50" id="AddBasket">
                        <button type="submit" style=" border: none; background: none; display: inline;">Add to card</button>
                    </span>
                </form>            
                <span class="text-black-50">@card.Price$</span>
            </div>
        </div>
    </div>
}