Models/Slider.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Fiorella_second.Models
{
    public class Slider
    {
        public int Id { get; set; }
        [Required]
        public string ImgUrl { get; set; }
        public DateTime? CreatedTime { get; set; }
        [NotMapped,Required]
        public IFormFile Photo { get; set; }
    }
}

Areas/AdminFiorella/Controllers/SliderController.cs
using Fiorella_second.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Fiorella_second.Areas.AdminFiorella.ViewModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Fiorella_second.Models;
using Fiorella_second.Utilities;
using Microsoft.AspNetCore.Hosting;
using Fiorella_second.Utilities.File;
using System.Collections.Generic;
using Fiorella_second.Services;
using System;
using Fiorella_second.ViewModel.Sliders;

namespace Fiorella_second.Areas.AdminFiorella.Controllers
{   [Area("AdminFiorella")]
    public class SliderController : Controller
    {
        private AppDbContext _context { get;}
        private IWebHostEnvironment _env {get;}
        private string _errorMessage;
        private int _maxCount=5;
        private LayoutServices _service { get; }

        public SliderController(AppDbContext context,IWebHostEnvironment env, LayoutServices service)
        {
            _context = context;
            _env = env;
            _service = service;
          
        }
        // GET: SliderController
        public async Task<IActionResult> Index()
        {
            Dictionary<string, string> settings = _service.GetSetting();
            int maxCount = Convert.ToInt32(settings["Slider_Max_Count"]);
            var setting = _context.Settings.AsEnumerable().ToDictionary(s => s.Key, s => s.Value);
            int sldCount = _context.Sliders.Count();
            TempData["SldCount"] = sldCount;
            TempData["MaxCount"] = maxCount;
            TablesVM TablesVM = new TablesVM
            {
        
            Sliders = await _context.Sliders.ToListAsync()
             };
            return View(TablesVM);
        }

        // GET: SliderController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SliderController/Create
        public ActionResult Create()
        {
            Dictionary<string, string> settings = _service.GetSetting();
            int maxCount = Convert.ToInt32(settings["Slider_Max_Count"]);
            var setting = _context.Settings.AsEnumerable().ToDictionary(s => s.Key, s => s.Value);
            int sldCount = _context.Sliders.Count();
            TempData["SldCount"] = sldCount;
            TempData["MaxCount"] = maxCount;

            return View();
        }

        // POST: SliderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MultipleSliderVM sliderVM)
        {

            #region MyRegion
            //Dictionary<string, string> settings = _service.GetSetting();
            //int size = Convert.ToInt32(settings["MaxImageSize"]);
            //var setting = _context.Settings.AsEnumerable().ToDictionary(s => s.Key, s => s.Value);
            //if (ModelState["Photo"].ValidationState == ModelValidationState.Invalid) return View();
            //foreach (var item in collection)
            //{

            //}
            //if (!slider.Photo.CheckFileType("image/"))
            //{
            //    //  ModelState.AddModelError("Photo", "File must be image type");
            //    throw new FieldAccessException("File must be image type");
            //    // return View();
            //}
            //if (!slider.Photo.CheckFileSize(size))
            //{
            //    ModelState.AddModelError($"Photo", "File size must be lest then " + $"{size}kb");
            //    return View();
            //}
            //string fileName = await slider.Photo.SaveFileAysnc(_env.WebRootPath, "img");
            //slider.ImgUrl = fileName;
            #endregion
           
            if (ModelState["Photos"].ValidationState == ModelValidationState.Invalid) return View();

           
            if (!CheckImageValid(sliderVM.Photos))
            {
                ModelState.AddModelError("Photos", _errorMessage);
                return View();
            }
            foreach (var photo in sliderVM.Photos)
            {
               
                  string fileName = await photo.SaveFileAysnc(_env.WebRootPath, "img");
                Slider slider = new Slider()
                {
                    ImgUrl = fileName
                };
                await _context.Sliders.AddAsync(slider);

            }


            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool CheckImageValid(List<IFormFile> photos)
        {
            Dictionary<string, string> settings = _service.GetSetting();
            int size = Convert.ToInt32(settings["MaxImageSize"]);
            int maxCount = Convert.ToInt32(settings["Slider_Max_Count"]);
            var setting = _context.Settings.AsEnumerable().ToDictionary(s => s.Key, s => s.Value);
            int count = 1;
            int sldCount = _context.Sliders.Count();
            foreach (var photo in photos)
            {             
                if (photos.Count>_maxCount-sldCount)
                {
                    _errorMessage = $"You can choose a maximum of {maxCount} photo ";
                    return false;
                }
               
                if (!photo.CheckFileType("image/"))
                {
                    _errorMessage = $"{photo.FileName} must be image type";
                    return false;
                }
                if (!photo.CheckFileSize(size))
                {
                    _errorMessage = $"{photo.FileName} size must be lest then " + $"{size}kb";
                    return false;
                }
                count++;
            }
            if (count > 5)
            {
                _errorMessage = $"must be 5 image ";
                return false;
            }

            return true;
        }

        // GET: SliderController/Edit/5

        public IActionResult Update(int id)
        {
           
            Slider slider = _context.Sliders.Find(id);
            if (slider == null) return NotFound();
            return View(slider);
        }

        // POST: SliderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, Slider slider)
        {
            try
            {
                Dictionary<string, string> settings = _service.GetSetting();
                int size = Convert.ToInt32(settings["MaxImageSize"]);
                int maxCount = Convert.ToInt32(settings["Slider_Max_Count"]);
                var setting = _context.Settings.AsEnumerable().ToDictionary(s => s.Key, s => s.Value);

                if (id != slider.Id) return BadRequest();
                if (ModelState["Photo"].ValidationState == ModelValidationState.Invalid) return View();
                Slider dbslider = await _context.Sliders.FindAsync(id);
                if (dbslider == null) return NotFound();
                if (!slider.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError($"Photo", "File must be image type");
                    // throw new FieldAccessException("File must be image type");
                    return View(dbslider);
                }
                if (!slider.Photo.CheckFileSize(size))
                {
                    ModelState.AddModelError($"Photo", "File size must be lest then " + $"{size}kb");
                    return View(dbslider);
                }
                Helper.RemoveFile(_env.WebRootPath, "img", dbslider.ImgUrl);
                string newFileName = await slider.Photo.SaveFileAysnc(_env.WebRootPath, "img");
                dbslider.ImgUrl = newFileName;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SliderController/Delete/5
      

        // POST: SliderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                Slider slider =  await _context.Sliders.FindAsync(id);
                if (slider == null) return NotFound();
                Helper.RemoveFile(_env.WebRootPath, "img", slider.ImgUrl);
                _context.Sliders.Remove(slider);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Areas/AdminFiorella/Views/Slider/Create.cshtml
@model MultipleSliderVM
@{
    ViewData["Title"] = "Create";
    int maxCount = Convert.ToInt32(@TempData["MaxCount"]);
    int dbCount = Convert.ToInt32(@TempData["SldCount"]);
    int rem = maxCount - dbCount;
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Add SLider Image Form</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <span class="text-warning d-block">Max Image Count: @maxCount</span>
                <span class="text-warning">Remaining Image: @rem</span>

                <div class="form-group">
                    <label asp-for="Photos">Choose Image</label>
                    <input asp-for="Photos" class="form-control" id="FileUpload1">
                    <span class="text-danger" asp-validation-for="Photos"></span>
                </div>
                @if (rem > 0)
                {
                    <button type="submit" class="btn btn-primary me-2">Submit</button>
                }
                else
                {
                    <button type="submit" class="btn btn-primary me-2" disabled>Submit</button>
                }
                <button class="btn btn-light" asp-action="Index">Cancel</button>
            </form>
        </div>
    </div>
</div>

Areas/AdminFiorella/Views/Slider/Index.cshtml
@model TablesVM
@{
    ViewData["Title"] = "Index";
    int count = 0;

    int maxCount = Convert.ToInt32(@TempData["MaxCount"]);

}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Category Table</h4>

            <div class="table-responsive">

                <table class="table table-hover">
                    <thead>
                        <tr>

                            <th style="align-items:center"> Image</th>
                            <th> Created Date</th>
                            <th>Setting</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var sld in Model.Sliders)
                        {
                            <tr>
                                <td>
                                    <img src="~/img/@sld.ImgUrl" alt="spotify" style="border-radius:0;width:200px;height:100px; object-fit:cover">
                                </td>
                                <td>
                                    <span>@sld.CreatedTime</span>
                                </td>


                                <td>
                                    <form asp-action="Delete" method="post" class="d-inline">
                                        <button id="complexConfirm" asp-action="Delete" asp-route-id="@sld.Id" type="submit" class="btn btn-danger me-2 ")"><i class="mdi mdi-trash-can" onclick="return confirm('Are you sure you want to delete this item?')" ></i></button>

                                    </form>
                                    <form asp-action="Update" method="post" class="d-inline">
                                        <a asp-action="Update" type="submit" title="Edit" class="btn btn-success me-2" asp-route-id="@sld.Id">
                                            <i class="mdi mdi-content-save-edit"></i>
                                        </a>
                                    </form>
                                    <button type="submit" class="btn btn-primary me-2"><i class="mdi mdi-information"></i></button>

                                </td>

                            </tr>
                            count++;
                        }

                    </tbody>
                </table>


                @if (count < maxCount)
                {
                    <a class="btn btn-success" asp-area="AdminFiorella" asp-controller="Slider" asp-action="Create">Add Image<i class="mdi mdi-creation"></i></a>
                }

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    function deleteOrder(Id)
{
        debugger;
        swal({
                title: "Are you sure?",
                text: "Are you sure that you want to delete this Order?",
                type: "warning",
                showCancelButton: true,
                closeOnConfirm: false,
                confirmButtonText: "Yes, delete it!",
                confirmButtonColor: "#ec6c62"
            },
            function()
             {
                $.ajax({
                    url: '/AdminFiorella/Slider/Delete',
                        data:
                  {
                            "SLiderID":Id 
                        },
                        type: "DELETE"
                    })
                    .done(function(data)
                          {
                        Swal.fire({
                            title: 'Are you sure?',
                            text: "You won't be able to revert this!",
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonColor: '#3085d6',
                            cancelButtonColor: '#d33',
                            confirmButtonText: 'Yes, delete it!'
                        }).then((result) => {
                            if (result.isConfirmed) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                )
                            }
                        })
                    })
                    .error(function(data)
                      {
                        swal("Oops", "We couldn't connect to the server!", "error");
                    });
            });
    }
</script> 

Areas/AdminFiorella/Views/Slider/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

@model Slider


<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Add SLider Image Form</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
               
                <div class="form-group">
                    <label asp-for="Photo">Choose Image</label>
                    <input asp-for="Photo" type="file" class="form-control">
                    <span class="text-danger" asp-validation-for="Photo"></span>
                </div>

                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-action="Index">Cancel</button>
            </form>
        </div>
    </div>
</div>